/** Run locally after installing Playwright Chromium: node --import tsx tests/browser-check.ts.
 * All services and test identities are local. No Supabase cloud project is modified.
 */
import { chromium, expect } from '@playwright/test';
import { createServer } from 'vite';
import { startFixture,fixtureKey } from './fixture';
import { createApp } from '../backend/src/app';
import { mkdir, readFile } from 'node:fs/promises';
import { randomBytes, pbkdf2Sync, createCipheriv } from 'node:crypto';
import { resolve } from 'node:path';
const fixture=await startFixture(54329);
const apiServer=await new Promise<ReturnType<ReturnType<typeof createApp>['listen']>>(resolveServer=>{const server=createApp({supabaseUrl:fixture.url,supabaseKey:fixtureKey,origins:['http://127.0.0.1:5173'],trustProxy:0}).listen(3001,'127.0.0.1',()=>resolveServer(server));});
process.env.VITE_SUPABASE_URL=fixture.url;process.env.VITE_SUPABASE_PUBLISHABLE_KEY=fixtureKey;process.env.VITE_API_URL='http://127.0.0.1:3001';
const vite=await createServer({root:resolve('frontend'),server:{host:'127.0.0.1',port:5173,strictPort:true}});await vite.listen();
const browser=await chromium.launch({...(process.env.TEST_CHROMIUM_PATH?{executablePath:process.env.TEST_CHROMIUM_PATH}:{}),headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
const checks:string[]=[];const passed=(s:string)=>{checks.push(s);console.log('PASS:',s);};
const nav=async(name:string)=>{await page.getByRole('navigation').getByRole('link',{name,exact:true}).click();};
const waitSaved=async()=>{await expect(page.locator('dialog')).toHaveCount(0,{timeout:20000});};
const close=async()=>{await page.getByRole('button',{name:'Close dialog',exact:true}).click();};
try{
 await page.goto('http://127.0.0.1:5173');await expect(page.getByRole('button',{name:'Open our private space'})).toBeVisible();passed('Login renders with no framework error');
 await page.getByLabel('Your email').fill('ivan@test.local');await page.getByLabel('Password',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Open our private space'}).click();await expect(page.getByText('Our favorite')).toBeVisible({timeout:20000});passed('Login reaches connected app through actual API');
 await page.getByRole('button',{name:'Add a memory',exact:false}).click();await page.getByLabel('Title',{exact:true}).fill('A day to remember');await page.getByLabel('The story').fill('A test memory of a little adventure together.');await page.getByLabel('Memory date').fill('2026-09-02');await page.getByLabel('Chapter',{exact:true}).fill('Little adventures');await page.locator('input[type=file]').setInputFiles(['frontend/public/icons/couple-192.png','frontend/public/icons/couple-512.png']);await page.getByRole('button',{name:'Save memory'}).click();await waitSaved();await expect(page.getByRole('heading',{name:'A day to remember'})).toBeVisible();passed('Create memory with two photos, date, caption, and chapter');
 await page.screenshot({path:'test-results/desktop-story.png',fullPage:true});
 await nav('Gallery');await page.getByLabel('Filter by chapter').selectOption('Little adventures');await page.getByRole('button',{name:'View photos: A day to remember'}).click();await expect(page.locator('#photo-number')).toHaveText('1 / 2');await page.getByRole('button',{name:'Next photo',exact:true}).click();await expect(page.locator('#photo-number')).toHaveText('2 / 2');await page.keyboard.press('ArrowLeft');await expect(page.locator('#photo-number')).toHaveText('1 / 2');await close();passed('Gallery chapter filter and photo viewer navigation');
 await page.getByRole('button',{name:'Favorite A day to remember',exact:true}).click();await expect(page.getByRole('button',{name:'Unfavorite A day to remember',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'Favorites',exact:false}).click();await expect(page.getByRole('heading',{name:'A day to remember'})).toBeVisible();passed('Favorites persist and filter gallery');
 await nav('Letters');await page.getByRole('button',{name:'Write a letter'}).click();await page.getByLabel('Open when…',{exact:true}).fill('you miss me');await page.getByLabel('Your letter').fill('Babi, there is always a little love waiting here for you.');await page.getByRole('button',{name:'Seal this letter'}).click();await waitSaved();await expect(page.getByText('Babi, there is always')).toHaveCount(0);await page.locator('.envelope').click();await expect(page.getByText('Babi, there is always a little love waiting here for you.')).toBeVisible();await close();passed('Create sealed letter and open its full message');
 await nav('Calendar');await page.getByRole('button',{name:'Next month',exact:true}).click();await page.getByRole('button',{name:'Previous month',exact:true}).click();await page.getByRole('button',{name:'Add a date',exact:false}).click();await page.getByLabel('Title',{exact:true}).fill('A birthday to celebrate');await page.getByLabel('Repeat').selectOption('yearly');await page.getByRole('button',{name:'Save date'}).click();await waitSaved();await expect(page.locator('.agenda').getByText('A birthday to celebrate')).toBeVisible();passed('Calendar navigation and recurring milestone creation');
 await nav('Bucket list');await page.getByRole('button',{name:'Add a dream'}).click();await page.getByLabel('Title',{exact:true}).fill('Watch the sunrise together');await page.getByLabel('The story').fill('A slow morning, coffee, and us.');await page.getByRole('button',{name:'Save dream'}).click();await waitSaved();await page.getByRole('button',{name:'Complete Watch the sunrise together',exact:true}).click();await expect(page.getByText('WE DID IT')).toBeVisible();await page.getByRole('button',{name:'Make this a memory'}).click();await page.getByLabel('Chapter',{exact:true}).fill('Our firsts');await page.locator('input[type=file]').setInputFiles('frontend/public/icons/couple-192.png');await page.getByRole('button',{name:'Save memory'}).click();await waitSaved();passed('Bucket-list completion and conversion into a photo memory');
 await nav('Playlist');await page.getByRole('button',{name:'Add a song'}).click();await page.getByLabel('Song title').fill('Our favorite song');await page.getByLabel('Artist',{exact:true}).fill('Our favorite artist');await page.getByLabel('Song link').fill('https://open.spotify.com/track/123456');await page.getByLabel('Why this song is ours').fill('It reminds me of you.');await page.getByRole('button',{name:'Save song'}).click();await waitSaved();await expect(page.getByRole('link',{name:'Play Our favorite song'})).toHaveAttribute('href','https://open.spotify.com/track/123456');await expect(page.locator('audio[autoplay],video[autoplay]')).toHaveCount(0);passed('Playlist stores song URL and note with intentional playback link');
 await nav('Our story');const first=page.locator('.timeline-card').filter({has:page.getByRole('heading',{name:'A day to remember'})});await first.getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Our little adventure');await page.getByRole('button',{name:'Save changes'}).click();await waitSaved();await expect(page.getByRole('heading',{name:'Our little adventure'})).toBeVisible();passed('Edit memory without losing photos');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/mobile-story.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByRole('navigation').getByRole('link')).toHaveCount(6);passed('Mobile 390 px layout has six navigation targets and no horizontal overflow');
 await page.getByRole('button',{name:'Lock',exact:true}).click();await page.getByLabel('Your email').fill('loraine@test.local');await page.getByLabel('Password',{exact:true}).fill('test-password-123');await page.getByRole('button',{name:'Open our private space'}).click();await expect(page.getByRole('heading',{name:'Our little adventure'})).toBeVisible({timeout:20000});passed('Second partner sees saved memories after a fresh login');
 await nav('Gallery');await page.locator('.gallery-card').filter({has:page.getByRole('heading',{name:'Our little adventure'})}).getByRole('button',{name:'Delete',exact:true}).click();await page.getByRole('button',{name:'Delete permanently'}).click();await waitSaved();await expect(page.getByRole('heading',{name:'Our little adventure'})).toHaveCount(0);passed('Partner can delete shared memory and attached photos');
 // Exercise original-format local decryption/import using a synthetic sealed fixture.
 const salt=randomBytes(16),iv=randomBytes(12),key=pbkdf2Sync('87654321',salt,600000,32,'sha256');
 const legacyPhoto=(await readFile('frontend/public/icons/couple-192.png')).toString('base64');
 const payload={version:1,html:'<figure><img src="photos/test.jpg" alt="Our old photo"><figcaption>A keepsake from before</figcaption></figure>',css:'',js:'',images:[{path:'photos/test.jpg',data:legacyPhoto}]};
 const cipher=createCipheriv('aes-256-gcm',key,iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(payload)),cipher.final()]);
 const sealed=Buffer.concat([Buffer.from('IVR1'),salt,iv,encrypted,cipher.getAuthTag()]);
 await page.route('**/legacy/scrapbook.sealed',route=>route.fulfill({status:200,body:sealed,contentType:'application/octet-stream'}));
 await page.getByRole('button',{name:'Open settings',exact:true}).click();await page.getByLabel('Original passcode',{exact:true}).fill('11111111');await page.getByRole('button',{name:'Import original photos',exact:true}).click();await expect(page.locator('#import-status')).toContainText('did not open',{timeout:20000});
 await page.getByLabel('Original passcode',{exact:true}).fill('87654321');await page.getByRole('button',{name:'Import original photos',exact:true}).click();await expect(page.locator('#import-status')).toContainText('Imported 1 photos',{timeout:20000});
 await page.getByLabel('Original passcode',{exact:true}).fill('87654321');await page.getByRole('button',{name:'Import original photos',exact:true}).click();await expect(page.locator('#import-status')).toContainText('Imported 0 photos',{timeout:20000});passed('Original-format passcode decryption rejects wrong codes, imports a photo, and skips duplicates');
 const exported=page.waitForEvent('download');await page.getByRole('button',{name:'Export our stories (JSON)',exact:true}).click();expect((await exported).suggestedFilename()).toMatch(/^ivraine-stories-/);await close();passed('Story export produces a downloadable JSON artifact');
 expect(errors).toEqual([]);passed('No uncaught browser runtime errors');
 console.log(JSON.stringify({passed:checks.length,errors}));
}catch(error){await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/failure.png',fullPage:true});console.error(await page.locator('body').innerText());throw error;}
finally{await browser.close();await vite.close();await new Promise<void>(resolve=>apiServer.close(()=>resolve()));await fixture.close();}
