const { useState, useEffect, useRef } = React;

const App = () => {
  const [messages, setMessages] = useState([]);
    const [input, setInput] = useState('');
      const [isTyping, setIsTyping] = useState(false);
        const chatMessagesRef = useRef(null);

          const productivitySuggestions = [
              'Set a timer for a Pomodoro session',
                  'Create a to-do list for today',
                      'Summarize my meeting notes',
                          'Suggest a productivity app',
                            ];

                              const handleSend = async () => {
                                  if (!input.trim()) return;

                                      const userMessage = { text: input, isUser: true };
                                          setMessages((prev) => [...prev, userMessage]);
                                              setInput('');
                                                  setIsTyping(true);

                                                      try {
                                                            const response = await fetch('https://virtuzen-model.onrender.com/api/chat', {
                                                                    method: 'POST',
                                                                            headers: { 'Content-Type': 'application/json' },
                                                                                    body: JSON.stringify({ message: input }),
                                                                                          });

                                                                                                if (!response.ok) throw new Error('Failed to fetch response');

                                                                                                      const data = await response.json();
                                                                                                            const botMessage = {
                                                                                                                    text: data.response?.candidates?.[0]?.content?.parts?.[0]?.text || 'Sorry, something went wrong!',
                                                                                                                            isUser: false,
                                                                                                                                  };
                                                                                                                                        setMessages((prev) => [...prev, botMessage]);
                                                                                                                                            } catch (error) {
                                                                                                                                                  setMessages((prev) => [
                                                                                                                                                          ...prev,
                                                                                                                                                                  { text: `Error: ${error.message}`, isUser: false },
                                                                                                                                                                        ]);
                                                                                                                                                                            } finally {
                                                                                                                                                                                  setIsTyping(false);
                                                                                                                                                                                      }
                                                                                                                                                                                        };

                                                                                                                                                                                          const handleSuggestionClick = (suggestion) => {
                                                                                                                                                                                              setInput(suggestion);
                                                                                                                                                                                                  setTimeout(() => handleSend(), 100);
                                                                                                                                                                                                    };

                                                                                                                                                                                                      const handleKeyPress = (e) => {
                                                                                                                                                                                                          if (e.key === 'Enter' && !e.shiftKey) {
                                                                                                                                                                                                                e.preventDefault();
                                                                                                                                                                                                                      handleSend();
                                                                                                                                                                                                                          }
                                                                                                                                                                                                                            };

                                                                                                                                                                                                                              useEffect(() => {
                                                                                                                                                                                                                                  if (chatMessagesRef.current) {
                                                                                                                                                                                                                                        chatMessagesRef.current.scrollTop = chatMessagesRef.current.scrollHeight;
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                              }, [messages]);

                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                    <div className="chat-container">
                                                                                                                                                                                                                                                          <header className="chat-header">
                                                                                                                                                                                                                                                                  <h1 className="text-xl font-bold">Productivity Assistant</h1>
                                                                                                                                                                                                                                                                          <button className="text-sm opacity-70 hover:opacity-100">
                                                                                                                                                                                                                                                                                    New Chat
                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                  </header>
                                                                                                                                                                                                                                                                                                        <div className="chat-messages" ref={chatMessagesRef}>
                                                                                                                                                                                                                                                                                                                {messages.map((msg, index) => (
                                                                                                                                                                                                                                                                                                                          <div key={index} className={`message ${msg.isUser ? 'user' : 'bot'}`}>
                                                                                                                                                                                                                                                                                                                                      {msg.text}
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                {isTyping && (
                                                                                                                                                                                                                                                                                                                                                                          <div className="message bot">
                                                                                                                                                                                                                                                                                                                                                                                      <div className="typing-indicator">
                                                                                                                                                                                                                                                                                                                                                                                                    <span></span><span></span><span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="chat-input-section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="chat-input"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setInput(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onKeyPress={handleKeyPress}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        placeholder="Ask for productivity tips..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  rows="2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="send-btn mt-2" onClick={handleSend}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Send
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="suggestions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {productivitySuggestions.map((suggestion, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                key={index}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="suggestion-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={() => handleSuggestionClick(suggestion)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {suggestion}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ReactDOM.render(<App />, document.getElementById('root'));